### ISSUE TITLE
More then one instance of xTableBox on one sheet.

### ISSUE THREAD

**Issue by tomchal** [ludberg/xTableBox#1]
Would be nice if it work...

**Comment by ludberg** [comment]
I just pushed an update that makes it possible to have several xTableBoxes on the same sheet. Let me know if you have any issues. 

Best
Anders

**Comment by tomchal** [comment]
Hi;

Cool , very handy. 

If you have too much timeJ I would suggest:
1. ```
     Left justify headers. With big text columns header is not visible.
   ```
2. ```
     Make it possible to multiselect with mouse drag. Or if too much work make it possible to CTRL+clik to make new selection. (Both like in standard list box). 
   ```

Anyway,  I’ll be more productive having this extension.

Regards

Tomasz

**Comment by ludberg** [comment]
Just pushed an update that enables drag select

**Comment by covenantbi** [comment]
Any chance we could get this updated for Nov 2018 sense server?  It is a much needed extension!
